apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: morpi-config
    envs:
      - config.env

namespace: morpi

resources:
  - ingress.yml
  - frontend/frontend-deployment.yml
  - frontend/frontend-service.yml
  - backend/backend-deployment.yml
  - backend/backend-service.yml
  - db/db-deployment.yml
  - db/db-service.yml
  - db/db-pvc.yml
