apiVersion: v1
kind: Service
metadata:
  name: morpi-frontend # Sets service name
  labels:
    app: morpi-frontend # Labels and Selectors
spec:
  type: ClusterIP # Sets service type
  ports:
    - port: 80
      name: http
  selector:
    app: frontend
